language: swift
osx_image: xcode10.1
branches:
  only:
    - develop
    - master

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem install xcpretty -N
  - make bootstrap

jobs:
  include:
    - stage: lint
      script:
        - swiftlint --reporter junit

    - stage: build
      script:
        - make build

    - stage: test
      script:
        - make test